version: '3.1'

services:

  db:
    image: postgres:12-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty



